"""Data models used by Deep Agent workflow."""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class DatasetSnapshot(BaseModel):
    """Represents raw records loaded from the source dataset."""

    dataset_name: str
    period: str
    records: list[dict[str, Any]]


class DataExplorationResult(BaseModel):
    """Contains quality and relationship findings from exploratory analysis."""

    row_count: int
    columns: list[str]
    null_ratio_by_column: dict[str, float]
    numeric_summary: dict[str, dict[str, float]]
    meaningful_correlations: list[dict[str, Any]]


class DetectedIssue(BaseModel):
    """Standard issue representation generated by rules and heuristics."""

    customer_id: str
    issue_type: str
    severity: str
    evidence: dict[str, Any]


class ImpactAssessment(BaseModel):
    """Estimated impact for each issue and aggregate totals."""

    issue_impacts: list[dict[str, Any]]
    total_monthly_revenue_at_risk_usd: float
    operational_load_index: float


class Recommendation(BaseModel):
    """Recommended products and solutions for a specific issue."""

    customer_id: str
    issue_type: str
    product_id: str
    solution_id: str
    rationale: str


class BusinessValidationResult(BaseModel):
    """Validation output to ensure findings are relevant and actionable."""

    approved: bool
    confidence: float = Field(ge=0.0, le=1.0)
    rejected_reasons: list[str]
    governance_notes: list[str]


class AnalysisReport(BaseModel):
    """Final report object emitted by the orchestrator."""

    exploration: DataExplorationResult
    issues: list[DetectedIssue]
    impact: ImpactAssessment
    recommendations: list[Recommendation]
    validation: BusinessValidationResult
    llm_summary: str
